# Generated by Django 4.2.27 on 2026-01-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('file', models.FileField(upload_to='consultations/', verbose_name='파일')),
                ('file_type', models.CharField(max_length=50, verbose_name='파일 타입')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('processing', '처리중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='상태')),
                ('analysis_result', models.TextField(blank=True, null=True, verbose_name='분석 결과')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일')),
            ],
            options={
                'verbose_name': '상담',
                'verbose_name_plural': '상담들',
                'ordering': ['-created_at'],
            },
        ),
    ]
