# Generated by Django 4.2.27 on 2026-01-07 06:27

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='original_content',
            field=models.TextField(blank=True, null=True, verbose_name='원본 내용'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='consultations/', verbose_name='파일'),
        ),
    ]
