# Generated by Django 4.2.27 on 2026-01-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_consultation_original_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='supabase_file_url',
            field=models.URLField(blank=True, null=True, verbose_name='Supabase 파일 URL'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='file',
            field=models.FileField(upload_to='consultations/', verbose_name='파일'),
        ),
    ]
