# Generated by Django 4.2.27 on 2026-01-08 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coaching', '0003_consultation_supabase_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
